### ISSUE TITLE
Multiple solr cores in one solr service

### ISSUE THREAD

**Issue by mrtronje** [lando/solr#2]
Is there a possability to use multiple cores in one Solr Service? Our CMS use this way of configuration for multiple languages (one solr core per language). 

I found this comment, but it doesn't give a hint how to achieve that: 

> @tanc is correct about the URLS. 
> it *might* be possible to support multiple cores in a single image but that should be a separate issue

_Originally posted by @pirog in https://github.com/lando/lando/issues/1123#issuecomment-453798883_

**Comment by GinovskiIvan** [comment]
Is there any update on this? Furthermore, could I ask, if multiple cores can be generated from the same solrconfig.xml file?

**Comment by oldeb** [comment]
Same here, stil trying to achieve a multisite configuration with 9 databases and 9 solr cores. Any help on the config would be great.

**Comment by vaccinemedia** [comment]
Same here - I have been using Drupal VM by Jeff Geerling https://github.com/geerlingguy/drupal-vm for a few years now but on a recent re-build from scratch none of my Drupal sites can delete content which is a very weird behaviour. There's no errors and my Wordpress sites on the same provisioned VM (I use it for LOTs of Drupal sites and a couple of Wordpress sites too) do not have this issue. When deleting content all I get is "there was an error" and that's about it. Nothing in the server logs or the Drupal logs either.

So as I'm now updating the Drupal projects to Drupal 10 and above I'm looking for a way of continuing development on these sites which is as easy as it was before using Drupal VM.

One of the sites is a multi-site installation where each site on the multi-site has it's own database and Solr Core and I'm currently up to 5 sites sharing the same codebase so any help here regarding having multiple Solr Cores would be amazing otherwise I'm either going to have to debug the Drupal VM or look for an alternative solution somewhere else but Lando looks like a good fit so far.

I'm a bit old school where my local dev usually mirrors the live server so I only have one VM running locally with all of my dev sites in there at the same time when I run "vagrant up" so with the Drupal VM I have all my sites in a folder in the Drupal VM folder called "sites" and have multiple websites and databases set in the config file.

**Comment by julien-langlois** [comment]
I have been using this configuration for several years, and it works without any problems.

```yaml
  solr:
    type: solr:8
    core: foobar
    build_as_root:
      - precreate-core foo /var/solr/data/foo
      - precreate-core bar /var/solr/data/bar
      - solr delete -c foobar -p 8983
    overrides:
      volumes:
        - ./conf/solr/foo:/var/solr/data/foo
        - ./conf/solr/bar:/var/solr/data/bar
        - ./data/solr/foo/data:/var/solr/data/foo/data
        - ./data/solr/bar/data:/var/solr/data/bar/data
```
