### ISSUE TITLE
Error when setting custom solr config

### ISSUE THREAD

**Issue by introfini** [lando/solr#24]
**My config:**

```
  solr:
    type: solr:8
    portforward: true
    core: cufpt
    config:
      dir: html/modules/contrib/search_api_solr/jump-start/solr8/config-set
```

**Error:**
```
solr_1        | lando 12:53:08.80 INFO  ==> Lando handing off to: /bin/sh -c /start-solr.sh html/modules/contrib/search_api_solr/jump-start/solr8/config-set
solr_1        | Executing /start-solr.sh html/modules/contrib/search_api_solr/jump-start/solr8/config-set
solr_1        | Booting solr with...
solr_1        | CORE: cufpt
solr_1        | CONFIG CUSTOM: html/modules/contrib/search_api_solr/jump-start/solr8/config-set
solr_1        | DATADIR: /var/solr/data
solr_1        | INSTALL DIR: /opt/solr
solr_1        | Executing /opt/docker-solr/scripts/precreate-core cufpt /solrconf
solr_1        | Core cufpt already exists
solr_1        | cp: cannot stat '/var/solr/data/cufpt/conf/.': Permission denied
```
