### ISSUE TITLE
Add custom plugins like solr-analysis-extras-9.8.1

### ISSUE THREAD

**Issue by AndreaCorda01** [lando/solr#58]
I have a Solr instance using lando and we need to add a new plugin solr-analysis-extras-9.8.1 to read the field ( class org.apache.solr.schema.ICUCollationField ).

The folder is: /opt/solr/server/solr-webapp/webapp/WEB-INF/lib/

```services:
  solr:
    type: solr:9.0
    portforward: true
    core: drupal
    config:
      dir: ./config/solr
```

Add a new system for Lando Solr to be capable to mount a plugin folder to be merged with the Solr internal folder

**Comment by ericgsmith** [comment]
Do you need to mount a plugin folder, or can you load the module with an environment var?

E.g.

```
services:
  solr:
    type: solr:9
    portforward: true
    core: drupal
    config:
      dir: config/solr
    overrides:
      environment:
        SOLR_MODULES: "extraction,langid,ltr,analysis-extras"
```
